package com.kun.flow.data;

import com.kun.flow.model.News;
import com.kun.flow.model.NewsExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewsMapper extends IMapper<News> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int countByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int deleteByExample(NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    List<News> selectByExample(NewsExample example);
    List<News>  listByCid(@Param("key") Long cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    News selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByExampleSelective(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByExample(@Param("record") News record, @Param("example") NewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NEWS
     *
     * @mbggenerated Fri Aug 08 12:56:51 CST 2014
     */
    int updateByPrimaryKey(News record);
	
	/* @param cid
     * @throws Exception
     */
}