package com.kun.flow.data;

import com.kun.flow.model.WebLogs;

public interface WebLogsMapper extends IMapper<WebLogs>{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    int insert(WebLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    int insertSelective(WebLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    WebLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    int updateByPrimaryKeySelective(WebLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblogs
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    int updateByPrimaryKey(WebLogs record);
}