package com.kun.flow.model;

import java.util.Date;

public class WebLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.id
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.operaterid
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private Integer operaterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.operation
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private String operation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.comments
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private String comments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.status
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblogs.operatetime
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    private Date operatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.id
     *
     * @return the value of weblogs.id
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.id
     *
     * @param id the value for weblogs.id
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.operaterid
     *
     * @return the value of weblogs.operaterid
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public Integer getOperaterid() {
        return operaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.operaterid
     *
     * @param operaterid the value for weblogs.operaterid
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setOperaterid(Integer operaterid) {
        this.operaterid = operaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.operation
     *
     * @return the value of weblogs.operation
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.operation
     *
     * @param operation the value for weblogs.operation
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.comments
     *
     * @return the value of weblogs.comments
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.comments
     *
     * @param comments the value for weblogs.comments
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.status
     *
     * @return the value of weblogs.status
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.status
     *
     * @param status the value for weblogs.status
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblogs.operatetime
     *
     * @return the value of weblogs.operatetime
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblogs.operatetime
     *
     * @param operatetime the value for weblogs.operatetime
     *
     * @mbggenerated Sun Aug 31 16:56:48 CST 2014
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }
}