package com.kun.flow.model;

public class NewsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.id
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    private Long id;

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    private Integer level;
    private Integer viewarticle;

    public Integer getViewarticle() {
        return viewarticle;
    }

    public void setViewarticle(Integer viewarticle) {
        this.viewarticle = viewarticle;
    }

    public Integer getArticleid() {
        return articleid;
    }

    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.name
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.status
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.parentid
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    private Long parentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.id
     *
     * @return the value of news_category.id
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.id
     *
     * @param id the value for news_category.id
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.name
     *
     * @return the value of news_category.name
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.name
     *
     * @param name the value for news_category.name
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.status
     *
     * @return the value of news_category.status
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.status
     *
     * @param status the value for news_category.status
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.parentid
     *
     * @return the value of news_category.parentid
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.parentid
     *
     * @param parentid the value for news_category.parentid
     *
     * @mbggenerated Fri Aug 08 16:19:05 CST 2014
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }
}