package com.kun.flow.model;

import java.util.Date;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.remark
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long operaterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String operaterCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.name
	 * @return  the value of role.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.name
	 * @param name  the value for role.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.remark
	 * @return  the value of role.remark
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.remark
	 * @param remark  the value for role.remark
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.createTime
	 * @return  the value of role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.createTime
	 * @param createTime  the value for role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.updateTime
	 * @return  the value of role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.updateTime
	 * @param updateTime  the value for role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.operaterId
	 * @return  the value of role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getOperaterId() {
		return operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.operaterId
	 * @param operaterId  the value for role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterId(Long operaterId) {
		this.operaterId = operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.operaterCode
	 * @return  the value of role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getOperaterCode() {
		return operaterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.operaterCode
	 * @param operaterCode  the value for role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterCode(String operaterCode) {
		this.operaterCode = operaterCode == null ? null : operaterCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role.status
	 * @return  the value of role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role.status
	 * @param status  the value for role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}