package com.kun.flow.model;

import java.util.Date;

public class RoleBindPermit {

    private Long categoryid;
    private Boolean editable;
    private Boolean auditable;

    public Long getCategoryid() {
        return categoryid;
    }

    public void setCategoryid(Long categoryid) {
        this.categoryid = categoryid;
    }

    public Boolean getEditable() {
        return editable;
    }

    public void setEditable(Boolean editable) {
        this.editable = editable;
    }

    public Boolean getAuditable() {
        return auditable;
    }

    public void setAuditable(Boolean auditable) {
        this.auditable = auditable;
    }

    public String getName() {
        return getfullname(permit.getName(),permit.getLevel());
    }

    public void setName(String name) {
        this.name = name;
    }

    private String getfullname(String name, Integer level) {
        StringBuffer buf = new StringBuffer();
        if(level!=null){
            if(level==2)
                buf.append("--");
            if(level==3)
                buf.append("----");
        }
        buf.append(name);
        return buf.toString();
    }
    private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.permitId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long permitId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long operaterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String operaterCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_bind_permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.id
	 * @return  the value of role_bind_permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.id
	 * @param id  the value for role_bind_permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.permitId
	 * @return  the value of role_bind_permit.permitId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getPermitId() {
		return permitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.permitId
	 * @param permitId  the value for role_bind_permit.permitId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setPermitId(Long permitId) {
		this.permitId = permitId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.roleId
	 * @return  the value of role_bind_permit.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.roleId
	 * @param roleId  the value for role_bind_permit.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.createTime
	 * @return  the value of role_bind_permit.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.createTime
	 * @param createTime  the value for role_bind_permit.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.updateTime
	 * @return  the value of role_bind_permit.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.updateTime
	 * @param updateTime  the value for role_bind_permit.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.operaterId
	 * @return  the value of role_bind_permit.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getOperaterId() {
		return operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.operaterId
	 * @param operaterId  the value for role_bind_permit.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterId(Long operaterId) {
		this.operaterId = operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.operaterCode
	 * @return  the value of role_bind_permit.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getOperaterCode() {
		return operaterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.operaterCode
	 * @param operaterCode  the value for role_bind_permit.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterCode(String operaterCode) {
		this.operaterCode = operaterCode == null ? null : operaterCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_bind_permit.status
	 * @return  the value of role_bind_permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_bind_permit.status
	 * @param status  the value for role_bind_permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	private Role role;
	private NewsCategory permit;

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public NewsCategory getPermit() {
		return permit;
	}

	public void setPermit(NewsCategory permit) {
		this.permit = permit;
	}
	
}