package com.kun.flow.model;

import java.util.Date;

public class OperaterBindRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.userId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long operaterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String operaterCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column operater_bind_role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.id
	 * @return  the value of operater_bind_role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.id
	 * @param id  the value for operater_bind_role.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.userId
	 * @return  the value of operater_bind_role.userId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.userId
	 * @param userId  the value for operater_bind_role.userId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.roleId
	 * @return  the value of operater_bind_role.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.roleId
	 * @param roleId  the value for operater_bind_role.roleId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.createTime
	 * @return  the value of operater_bind_role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.createTime
	 * @param createTime  the value for operater_bind_role.createTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.updateTime
	 * @return  the value of operater_bind_role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.updateTime
	 * @param updateTime  the value for operater_bind_role.updateTime
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.operaterId
	 * @return  the value of operater_bind_role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getOperaterId() {
		return operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.operaterId
	 * @param operaterId  the value for operater_bind_role.operaterId
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterId(Long operaterId) {
		this.operaterId = operaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.operaterCode
	 * @return  the value of operater_bind_role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getOperaterCode() {
		return operaterCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.operaterCode
	 * @param operaterCode  the value for operater_bind_role.operaterCode
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOperaterCode(String operaterCode) {
		this.operaterCode = operaterCode == null ? null : operaterCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column operater_bind_role.status
	 * @return  the value of operater_bind_role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column operater_bind_role.status
	 * @param status  the value for operater_bind_role.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}