package com.kun.flow.model;

public class NewsCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.id
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.name
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_category.status
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.id
     *
     * @return the value of news_category.id
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.id
     *
     * @param id the value for news_category.id
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.name
     *
     * @return the value of news_category.name
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.name
     *
     * @param name the value for news_category.name
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_category.status
     *
     * @return the value of news_category.status
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_category.status
     *
     * @param status the value for news_category.status
     *
     * @mbggenerated Wed Jul 16 16:45:51 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}