package com.kun.flow.model;

public class Permit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.code
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.leaf
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer leaf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column permit.ordinal
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	private Integer ordinal;
	
	private Integer roleId;
	
	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.id
	 * @return  the value of permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.id
	 * @param id  the value for permit.id
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.name
	 * @return  the value of permit.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.name
	 * @param name  the value for permit.name
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.code
	 * @return  the value of permit.code
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.code
	 * @param code  the value for permit.code
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.leaf
	 * @return  the value of permit.leaf
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getLeaf() {
		return leaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.leaf
	 * @param leaf  the value for permit.leaf
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setLeaf(Integer leaf) {
		this.leaf = leaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.status
	 * @return  the value of permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.status
	 * @param status  the value for permit.status
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column permit.ordinal
	 * @return  the value of permit.ordinal
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public Integer getOrdinal() {
		return ordinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column permit.ordinal
	 * @param ordinal  the value for permit.ordinal
	 * @mbggenerated  Thu Apr 24 23:56:12 CST 2014
	 */
	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}
}